/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VisualisationRouteImport } from './routes/visualisation'
import { Route as DatasetsRouteImport } from './routes/datasets'
import { Route as AiAnalysisRouteImport } from './routes/ai-analysis'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RunsRunIdRouteImport } from './routes/runs.$runId'
import { Route as AiAnalysisResultsRouteImport } from './routes/ai-analysis.results'

const VisualisationRoute = VisualisationRouteImport.update({
  id: '/visualisation',
  path: '/visualisation',
  getParentRoute: () => rootRouteImport,
} as any)
const DatasetsRoute = DatasetsRouteImport.update({
  id: '/datasets',
  path: '/datasets',
  getParentRoute: () => rootRouteImport,
} as any)
const AiAnalysisRoute = AiAnalysisRouteImport.update({
  id: '/ai-analysis',
  path: '/ai-analysis',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RunsRunIdRoute = RunsRunIdRouteImport.update({
  id: '/runs/$runId',
  path: '/runs/$runId',
  getParentRoute: () => rootRouteImport,
} as any)
const AiAnalysisResultsRoute = AiAnalysisResultsRouteImport.update({
  id: '/results',
  path: '/results',
  getParentRoute: () => AiAnalysisRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ai-analysis': typeof AiAnalysisRouteWithChildren
  '/datasets': typeof DatasetsRoute
  '/visualisation': typeof VisualisationRoute
  '/ai-analysis/results': typeof AiAnalysisResultsRoute
  '/runs/$runId': typeof RunsRunIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ai-analysis': typeof AiAnalysisRouteWithChildren
  '/datasets': typeof DatasetsRoute
  '/visualisation': typeof VisualisationRoute
  '/ai-analysis/results': typeof AiAnalysisResultsRoute
  '/runs/$runId': typeof RunsRunIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ai-analysis': typeof AiAnalysisRouteWithChildren
  '/datasets': typeof DatasetsRoute
  '/visualisation': typeof VisualisationRoute
  '/ai-analysis/results': typeof AiAnalysisResultsRoute
  '/runs/$runId': typeof RunsRunIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ai-analysis'
    | '/datasets'
    | '/visualisation'
    | '/ai-analysis/results'
    | '/runs/$runId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ai-analysis'
    | '/datasets'
    | '/visualisation'
    | '/ai-analysis/results'
    | '/runs/$runId'
  id:
    | '__root__'
    | '/'
    | '/ai-analysis'
    | '/datasets'
    | '/visualisation'
    | '/ai-analysis/results'
    | '/runs/$runId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AiAnalysisRoute: typeof AiAnalysisRouteWithChildren
  DatasetsRoute: typeof DatasetsRoute
  VisualisationRoute: typeof VisualisationRoute
  RunsRunIdRoute: typeof RunsRunIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/visualisation': {
      id: '/visualisation'
      path: '/visualisation'
      fullPath: '/visualisation'
      preLoaderRoute: typeof VisualisationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/datasets': {
      id: '/datasets'
      path: '/datasets'
      fullPath: '/datasets'
      preLoaderRoute: typeof DatasetsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-analysis': {
      id: '/ai-analysis'
      path: '/ai-analysis'
      fullPath: '/ai-analysis'
      preLoaderRoute: typeof AiAnalysisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/runs/$runId': {
      id: '/runs/$runId'
      path: '/runs/$runId'
      fullPath: '/runs/$runId'
      preLoaderRoute: typeof RunsRunIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-analysis/results': {
      id: '/ai-analysis/results'
      path: '/results'
      fullPath: '/ai-analysis/results'
      preLoaderRoute: typeof AiAnalysisResultsRouteImport
      parentRoute: typeof AiAnalysisRoute
    }
  }
}

interface AiAnalysisRouteChildren {
  AiAnalysisResultsRoute: typeof AiAnalysisResultsRoute
}

const AiAnalysisRouteChildren: AiAnalysisRouteChildren = {
  AiAnalysisResultsRoute: AiAnalysisResultsRoute,
}

const AiAnalysisRouteWithChildren = AiAnalysisRoute._addFileChildren(
  AiAnalysisRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AiAnalysisRoute: AiAnalysisRouteWithChildren,
  DatasetsRoute: DatasetsRoute,
  VisualisationRoute: VisualisationRoute,
  RunsRunIdRoute: RunsRunIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
